---
title: "Using the assignment4shiny package"
author: "Rishab Aswani"
output: html_document
---

## Introduction

This vignette provides an overview of how to use the `assignment4shiny` package, which includes a Shiny app and some basic data manipulation functions.

## Installation

To install the package from GitHub:

```{r}
remotes::install_github("ETC5523-2024/assignment4shiny")
```


```{r}
library(assignment4shiny)
launchApp()

```


```{r}
devtools::document()


```

```{r}
#' @title Launch the Shiny App
#'
#' @description This function launches the Shiny application contained in the package.
#'
#' @return No return value, called for side effects.
#' @export
launchApp <- function() {
  shiny::runApp(system.file("app", package = "assignment4shiny"))
}

```


```{r}
devtools::document()

```
```{r}
?launchApp  # This will display the documentation for launchApp()
?cleaned_data  # This will display the documentation for the cleaned dataset

```

```{r}
export(launchApp)

```
```{r}
#' @title Launch the Shiny App
#' @description This function launches the Shiny application contained in the package.
#' @return No return value, called for side effects.
#' @export
launchApp <- function() {
  shiny::runApp(system.file("app", package = "assignment4shiny"))
}

```

```{r}
devtools::document()
export(launchApp)
?launchApp

```
```{r}

library(roxygen2)

devtools::document()
?launchApp


#' @title Launch the Shiny App
#' @description This function launches the Shiny application contained in the package.
#' @return No return value, called for side effects.
#' @export
launchApp <- function() {
  shiny::runApp(system.file("app", package = "assignment4shiny"))
}

devtools::document()

?launchApp

```
```{r}
devtools::document()
??launchApp

```

